development:
  adapter: postgresql
  database: unicode
  database: development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  database: unicode
  database: test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  database: unicode
  database: production
  pool: 5
  username: postgres
  password:
